# Generated by Django 3.2.25 on 2024-09-02 22:59

from django.db import migrations, models
import django.db.models.deletion
import saleor.core.utils.json_serializer
import saleor.webhook.models
import saleor.webhook.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('target_url', saleor.webhook.models.WebhookURLField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('secret_key', models.CharField(blank=True, max_length=255, null=True)),
                ('subscription_query', models.TextField(blank=True, null=True)),
                ('custom_headers', models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True, validators=[saleor.webhook.validators.custom_headers_validator])),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='app.app')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=128, verbose_name='Event type')),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='webhook.webhook')),
            ],
        ),
    ]
