# Generated by Django 3.2.25 on 2024-09-02 22:59

from django.db import migrations, models
import django.db.models.deletion
import saleor.core.utils.json_serializer


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=False)),
                ('configuration', models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='channel.channel')),
            ],
            options={
                'permissions': (('manage_plugins', 'Manage plugins'),),
                'unique_together': {('identifier', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('plugin_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='plugins.pluginconfiguration')),
            ],
        ),
    ]
