# Generated by Django 3.2.25 on 2024-09-02 22:59

from django.db import migrations, models
import django.utils.timezone
import tenant_schemas.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.CharField(max_length=128, unique=True)),
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('paid_until', models.DateField()),
                ('on_trial', models.BooleanField(default=False)),
                ('created_at', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('admin_phone', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('admin_email', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('admin_phone', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('admin_email', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('domain_url', models.CharField(blank=True, default=None, max_length=64, null=True)),
            ],
        ),
    ]
