# Generated by Django 3.2.25 on 2024-08-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_auto_20240828_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('admin_phone', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('admin_email', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('domain_url', models.CharField(blank=True, default=None, max_length=64, null=True)),
            ],
        ),
    ]
