# Generated by Django 4.2.15 on 2024-09-04 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_auto_20240904_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('admin_phone', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('admin_email', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('domain_url', models.CharField(blank=True, default=None, max_length=64, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='admin_email',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='admin_phone',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='client',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='on_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='paid_until',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
