# Generated by Django 3.2.25 on 2024-09-02 22:59

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('giftcard', '0001_initial'),
        ('account', '0001_initial'),
        ('order', '0001_initial'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcardevent',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order'),
        ),
        migrations.AddField(
            model_name='giftcardevent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_card_events', to='account.user'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.app'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account.user'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='fulfillment_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_cards', to='order.fulfillmentline'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_cards', to='product.product'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='tags',
            field=models.ManyToManyField(related_name='gift_cards', to='giftcard.GiftCardTag'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='used_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_cards', to='account.user'),
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='giftcard_tsearch'),
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=django.contrib.postgres.indexes.GinIndex(fields=['private_metadata'], name='giftcard_p_meta_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='giftcard_meta_idx'),
        ),
    ]
