# Generated by Django 3.2.25 on 2024-09-02 22:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import saleor.core.utils.json_serializer


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('deleted', 'Deleted')], default='pending', max_length=50)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_file', models.FileField(null=True, upload_to='export_files')),
                ('app', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='export_files', to='app.app')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='export_files', to='account.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExportEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('type', models.CharField(choices=[('export_pending', 'Data export was started.'), ('export_success', 'Data export was completed successfully.'), ('export_failed', 'Data export failed.'), ('export_deleted', 'Export file was deleted.'), ('exported_file_sent', 'Email with link to download file was sent to the customer.'), ('Export_failed_info_sent', 'Email with info that export failed was sent to the customer.')], max_length=255)),
                ('parameters', models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('app', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_csv_events', to='app.app')),
                ('export_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='csv.exportfile')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_csv_events', to='account.user')),
            ],
        ),
    ]
